import { PriceNameType } from "@/types/dish";

export const menuProducts = [
  { id: "0", name: "Spaghetti alle vongole", category: "Primi Piatti", ingredients: "Pasta con vongole fresche, aglio, prezzemolo e peperoncino.", description: "Pasta con vongole fresche, aglio, prezzemolo e peperoncino", prices: [{ name: PriceNameType.STANDARD, price: 15 }], imageUrl: "/api/serve-image?filename=1787049384026-405732908.webp", bestSeller: true, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Molluschi e derivati"] },
  { id: "1", name: "Risotto ai funghi", category: "Primi Piatti", ingredients: "Riso carnaroli con porcini, burro e parmigiano.", description: "Riso carnaroli con porcini, burro e parmigiano.", prices: [{ name: PriceNameType.STANDARD, price: 14 }], imageUrl: "/api/serve-image?filename=1787049384174-123317945.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Latte e lattosio"] },
  { id: "2", name: "Gnocchi di patate burro e salvia", category: "Primi Piatti", ingredients: "Gnocchi fatti in casa conditi con burro fuso e foglie di salvia.", description: "Gnocchi fatti in casa conditi con burro fuso e foglie di salvia.", prices: [{ name: PriceNameType.STANDARD, price: 11 }], imageUrl: "/api/serve-image?filename=1787049384323-292979384.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Uova e prodotti a base di uova", "Latte e lattosio"] },
  { id: "3", name: "Tagliatelle al ragù", category: "Primi Piatti", ingredients: "Pasta all'uovo con ragù di carne lento e pomodoro.", description: "Pasta all'uovo con ragù di carne lento e pomodoro.", prices: [{ name: PriceNameType.STANDARD, price: 13 }], imageUrl: "/api/serve-image?filename=1787049384455-625355834.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Uova e prodotti a base di uova", "Sedano"] },
  { id: "4", name: "Penne al salmone", category: "Primi Piatti", ingredients: "Pasta con salmone affumicato, panna e erbe aromatiche.", description: "Pasta con salmone affumicato, panna e erbe aromatiche.", prices: [{ name: PriceNameType.STANDARD, price: 15 }], imageUrl: "/api/serve-image?filename=1787049384593-941122783.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Pesce e derivati", "Latte e lattosio"] },
  { id: "5", name: "Cotoletta alla milanese", category: "Secondi Piatti", ingredients: "Vitello impanato e fritto nel burro con limone.", description: "Vitello impanato e fritto nel burro con limone.", prices: [{ name: PriceNameType.STANDARD, price: 16 }], imageUrl: "/api/serve-image?filename=1787049384730-645220752.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Uova e prodotti a base di uova", "Latte e lattosio"] },
  { id: "6", name: "Pollo alla cacciatora", category: "Secondi Piatti", ingredients: "Pollo stufato con pomodoro, olive, capperi e rosmarino.", description: "Pollo stufato con pomodoro, olive, capperi e rosmarino.", prices: [{ name: PriceNameType.STANDARD, price: 14 }], imageUrl: "/api/serve-image?filename=1787049384867-697376836.webp", bestSeller: false, allergens: ["Sedano", "Solfiti (sopra 10 mg/l)"] },
  { id: "7", name: "Baccalà mantecato", category: "Secondi Piatti", ingredients: "Baccalà cremoso con olio e polenta morbida.", description: "Baccalà cremoso con olio e polenta morbida.", prices: [{ name: PriceNameType.STANDARD, price: 15 }], imageUrl: "/api/serve-image?filename=1787049385004-641085232.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Pesce e derivati"] },
  { id: "8", name: "Arrosto di maiale", category: "Secondi Piatti", ingredients: "Lombata di maiale al forno con latte e aromi.", description: "Lombata di maiale al forno con latte e aromi.", prices: [{ name: PriceNameType.STANDARD, price: 17 }], imageUrl: "/api/serve-image?filename=1787049385093-861022567.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Latte e lattosio", "Sedano"] },
  { id: "9", name: "Filetto al pepe verde", category: "Secondi Piatti", ingredients: "Manzo grigliato con salsa al brandy e pepe verde.", description: "Manzo grigliato con salsa al brandy e pepe verde.", prices: [{ name: PriceNameType.STANDARD, price: 20 }], imageUrl: "/api/serve-image?filename=1787049385229-13820348.webp", bestSeller: false, allergens: ["Senape", "Solfiti (sopra 10 mg/l)"] },
  { id: "10", name: "Patate arrosto", category: "Contorni", ingredients: "Patate novelle al forno con rosmarino e olio extravergine.", description: "Patate novelle al forno con rosmarino e olio extravergine.", prices: [{ name: PriceNameType.STANDARD, price: 5 }], imageUrl: "/api/serve-image?filename=1787049385366-424937928.webp", bestSeller: false },
  { id: "11", name: "Spinaci saltati", category: "Contorni", ingredients: "Spinaci freschi trifolati con aglio e limone.", description: "Spinaci freschi trifolati con aglio e limone.", prices: [{ name: PriceNameType.STANDARD, price: 5 }], imageUrl: "/api/serve-image?filename=1787049385505-445856704.webp", bestSeller: false },
  { id: "12", name: "Carote al vapore", category: "Contorni", ingredients: "Carote baby cotte al vapore con prezzemolo.", description: "Carote baby cotte al vapore con prezzemolo.", prices: [{ name: PriceNameType.STANDARD, price: 4 }], imageUrl: "/api/serve-image?filename=1787049385651-905501243.webp", bestSeller: false },
  { id: "13", name: "Broccoli al curry", category: "Contorni", ingredients: "Broccoli lessati con spezie leggere e olio.", description: "Broccoli lessati con spezie leggere e olio.", prices: [{ name: PriceNameType.STANDARD, price: 5 }], imageUrl: "/api/serve-image?filename=1787049385840-866310034.webp", bestSeller: false },
  { id: "14", name: "Insalata mista", category: "Contorni", ingredients: "Misticanza fresca con olio e aceto balsamico.", description: "Misticanza fresca con olio e aceto balsamico.", prices: [{ name: PriceNameType.STANDARD, price: 4 }], imageUrl: "/api/serve-image?filename=1787049385968-964207983.webp", bestSeller: false },
  { id: "15", name: "Tiramisù", category: "Dolci", ingredients: "Mascarpone, caffè, savoiardi e cacao amaro.", description: "Mascarpone, caffè, savoiardi e cacao amaro.", prices: [{ name: PriceNameType.STANDARD, price: 7 }], imageUrl: "/api/serve-image?filename=1787049386073-543059543.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Uova e prodotti a base di uova", "Latte e lattosio"] },
  { id: "16", name: "Panna cotta", category: "Dolci", ingredients: "Crema di panna cotta con coulis di frutti di bosco.", description: "Crema di panna cotta con coulis di frutti di bosco.", prices: [{ name: PriceNameType.STANDARD, price: 6 }], imageUrl: "/api/serve-image?filename=1787049386144-37257487.webp", bestSeller: false, allergens: ["Latte e lattosio"] },
  { id: "17", name: "Crostata di frutta", category: "Dolci", ingredients: "Pasta frolla con crema pasticcera e frutta fresca.", description: "Pasta frolla con crema pasticcera e frutta fresca.", prices: [{ name: PriceNameType.STANDARD, price: 7 }], imageUrl: "/api/serve-image?filename=1787049386271-650416033.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Uova e prodotti a base di uova", "Latte e lattosio"] },
  { id: "18", name: "Zabaione", category: "Dolci", ingredients: "Crema con tuorli, zucchero e marsala caldo.", description: "Crema con tuorli, zucchero e marsala caldo.", prices: [{ name: PriceNameType.STANDARD, price: 6 }], imageUrl: "/api/serve-image?filename=1787049386383-27420003.webp", bestSeller: false, allergens: ["Uova e prodotti a base di uova", "Solfiti (sopra 10 mg/l)"] },
  { id: "19", name: "Cheesecake al limone", category: "Dolci", ingredients: "Base di biscotti con crema al formaggio e limone.", description: "Base di biscotti con crema al formaggio e limone.", prices: [{ name: PriceNameType.STANDARD, price: 7 }], imageUrl: "/api/serve-image?filename=1787049386480-679492360.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Latte e lattosio"] },
  { id: "20", name: "Spritz", category: "Bevande", ingredients: "Aperol, prosecco, soda e arancia.", description: "Aperol, prosecco, soda e arancia.", prices: [{ name: PriceNameType.STANDARD, price: 6 }], imageUrl: "/api/serve-image?filename=1787049386588-3608306.webp", bestSeller: false, allergens: ["Solfiti (sopra 10 mg/l)"] },
  { id: "21", name: "Vino rosso Chianti", category: "Bevande", ingredients: "Vino toscano strutturato da sangiovese.", description: "Vino toscano strutturato da sangiovese.", prices: [{ name: PriceNameType.STANDARD, price: 8 }], imageUrl: "/api/serve-image?filename=1787049386755-951399847.webp", bestSeller: false, allergens: ["Solfiti (sopra 10 mg/l)"] },
  { id: "22", name: "Birra artigianale", category: "Bevande", ingredients: "Lager italiana non filtrata.", description: "Lager italiana non filtrata.", prices: [{ name: PriceNameType.STANDARD, price: 5 }], imageUrl: "/api/serve-image?filename=1787049386867-258212768.webp", bestSeller: false, allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)"] },
  { id: "23", name: "Caffè espresso", category: "Bevande", ingredients: "Espresso napoletano puro.", description: "Espresso napoletano puro.", prices: [{ name: PriceNameType.STANDARD, price: 1.5 }], imageUrl: "/api/serve-image?filename=1787049386987-103591403.webp", bestSeller: false },
  { id: "24", name: "Acqua naturale", category: "Bevande", ingredients: "Acqua frizzante o naturale da fonte italiana.", description: "Acqua frizzante o naturale da fonte italiana.", prices: [{ name: PriceNameType.STANDARD, price: 2 }], imageUrl: "/api/serve-image?filename=1787049387015-100930125.webp", bestSeller: false }
];
