export const themeColors = {
  layout: {
    background: "#f3eadc",
    homeButtonColor: "#f4ead8",
    homeButtonTextColor: "#1c1610",
  },
  navbar: {
    background: "#1c1610",
    logoColor: "#d4b56a",
    textColor: "#f4ead8",
    buttonBackground: "#d4b56a",
    buttonText: "#1c1610",
    buttonHover: "#e4c888",
    iconColor: "#f4ead8",
  },
  sidebar: {
    background: "#1c1610",
    titleColor: "#f4ead8",
    menuItemBackground: "#1c1610",
    menuItemColor: "#f4ead8",
    menuItemActive: "#d4b56a",
    menuItemHover: "#e4c888",
    iconColor: "#d4b56a",
  },
  drawer: {
    background: "#1c1610",
    titleColor: "#f4ead8",
    menuItemColor: "#f4ead8",
    footerTextColor: "#d7cbb8",
  },
  card: {
    backgroundImage: "",
    backgroundOpacity: 1,
    backgroundColor: "#fffaf3",
    bestSellerTagColor: "#8a6a2e",
    productNameColor: "#1c1610",
    priceColor: "#8a6a2e",
    ingredientsColor: "#6a5e52",
    detailsButtonBackground: "#1c1610",
    detailsButtonIcon: "#f4ead8",
    subtitleColor: "#1c1610",
    detailsIngredientsColor: "#6a5e52",
    descriptionTextColor: "#6a5e52",
    shadowColor: "#1c1610",
    shadowOpacity: 0.08,
    hoverShadowOpacity: 0.14,
    borderRadius: 18,
    borderColor: "#ead9c0",
    borderWidth: 1,
    detailsBorderColor: "#ead9c0",
    detailsBorderWidth: 1,
    allergenTagColor: "#8a6a2e",
    allergenTextColor: "#fffaf3",
    viewMode: "carousel",
  },
  sections: {
    titleColor: "#1c1610",
    descriptionColor: "#6a5e52",
  },
  footer: {
    background: "#1c1610",
    textColor: "#d7cbb8",
    linkHoverOpacity: 0.8,
  },
  modelViewer: {
    ambientIntensity: 2,
  },
};
