import { TRestaurant, PriceNameType } from "@/types/dish";

//*** Mock data ***
export const dishes: TRestaurant = {
  name: "Menucolcodice.it",
  description: "Il Menù digitale",
  address: {
    street: "Via Roma 100",
    city: "Salerno",
    state: "Salerno",
    postalCode: "84121",
    country: "Italia",
  },
  phone: "+39 000 000000",
  email: "info@menucolcodice.com",
  website: "https://menucolcodice.it",
  menuPageTitle: "Menucolcodice.it",
  openingHours: "Lun-Sab: 12:00/00:00 - Dom: Chiuso",
  footerText: " Menucolcodice.it © 2026 ",
  social: {
    facebook: "https://www.facebook.com/Menucolcodice",
    instagram: "https://www.instagram.com/Menucolcodice",
    whatsapp: "+39 000 000000",
    glovo: "https://glovoapp.com/",
    deliveroo: "https://deliveroo.it/",
    justeat: "https://justeat.it/",
  },
  logoType: "image",
  logoUrl: "/api/serve-image?filename=1769590154989-965810215.png",
  logoWidth: 150,
  logoHeight: 50,
  faviconUrl: "/api/serve-image?filename=1769590150078-509909973.png",
  homeBackgroundUrl: "/api/serve-image?filename=1769610702768-279486805.jpg",
  homeBackgroundType: "image",
  homeBackgroundVideoUrl: "/uploads/1769591626927-465543061.mp4",
  whatsappButtonColor: "#25D366",
  whatsappIconColor: "#ffffff",
  socialButtonColor: "#0c5648",
  socialIconColor: "#ffffff",
  iubendaScriptUrl: "",
  iubendaPrivacyPolicyUrl: "",
  iubendaCookiePolicyUrl: "",
  themeColors: {
    layout: {
      background: "#a1cec6",
      homeButtonColor: "#ffffff",
      homeButtonTextColor: "#00374a",
    },
    navbar: {
      background: "#0a5648",
      logoColor: "#ffffff",
      textColor: "#000000",
      buttonBackground: "#00a88c",
      buttonText: "#ffffff",
      buttonHover: "#7ad6c7",
      iconColor: "#ffffff",
    },
    sidebar: {
      background: "#0a5648",
      titleColor: "#ffffff",
      menuItemBackground: "#18af96",
      menuItemColor: "#ffffff",
      menuItemActive: "#4f8c82",
      menuItemHover: "#d9d9d9",
      iconColor: "#ffffff",
    },
    drawer: {
      background: "#93b8b2",
      titleColor: "#0c5648",
      menuItemColor: "#ffffff",
      footerTextColor: "#000000",
    },
    card: {
      backgroundImage: "",
      backgroundOpacity: 0.2,
      backgroundColor: "#86c1b6",
      bestSellerTagColor: "#0c5648",
      productNameColor: "#0a5648",
      priceColor: "#0c5648",
      ingredientsColor: "#ffffff",
      detailsButtonBackground: "#004d40",
      detailsButtonIcon: "#ffffff",
      subtitleColor: "#0c5648",
      detailsIngredientsColor: "#616161",
      descriptionTextColor: "#616161",
      shadowColor: "#000000",
      shadowOpacity: 0.1,
      hoverShadowOpacity: 0.15,
      borderRadius: 12,
      borderColor: "#0c5648",
      borderWidth: 1,
      detailsBorderColor: "#ffffff",
      detailsBorderWidth: 1,
      allergenTagColor: "#ffffff",
      allergenTextColor: "#0c5648",
      viewMode: "carousel",
    },
    sections: {
      titleColor: "#0c5648",
      descriptionColor: "#616161",
    },
    footer: {
      background: "#0c5648",
      textColor: "#ffffff",
      linkHoverOpacity: 0.8,
    },
    modelViewer: {
      ambientIntensity: 2,
    },
  },
  sections: [
    {
      name: "Primi Piatti",
      description: "le nostre specialità fatte in casa",
      order: 1,
      items: [
        {
          id: "0",
          name: "Spaghetti alle vongole",
          ingredients: "Pasta con vongole fresche, aglio, prezzemolo e peperoncino.",
          description: "Pasta con vongole fresche, aglio, prezzemolo e peperoncino",
          prices: [{ name: PriceNameType.STANDARD, price: 12 }],
          imageUrl: "/api/serve-image?filename=1787049384026-405732908.webp",
          bestSeller: true,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Molluschi e derivati"],
        },
        {
          id: "1",
          name: "Risotto ai funghi",
          ingredients: "Riso carnaroli con porcini, burro e parmigiano.",
          description: "Riso carnaroli con porcini, burro e parmigiano.",
          prices: [{ name: PriceNameType.STANDARD, price: 14 }],
          imageUrl: "/api/serve-image?filename=1787049384174-123317945.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Latte e lattosio"],
        },
        {
          id: "2",
          name: "Gnocchi di patate burro e salvia",
          ingredients: "Gnocchi fatti in casa conditi con burro fuso e foglie di salvia.",
          description: "Gnocchi fatti in casa conditi con burro fuso e foglie di salvia.",
          prices: [{ name: PriceNameType.STANDARD, price: 11 }],
          imageUrl: "/api/serve-image?filename=1787049384323-292979384.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Uova e prodotti a base di uova", "Latte e lattosio"],
        },
        {
          id: "3",
          name: "Tagliatelle al ragù",
          ingredients: "Pasta all'uovo con ragù di carne lento e pomodoro.",
          description: "Pasta all'uovo con ragù di carne lento e pomodoro.",
          prices: [{ name: PriceNameType.STANDARD, price: 13 }],
          imageUrl: "/api/serve-image?filename=1787049384455-625355834.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Uova e prodotti a base di uova", "Sedano"],
        },
        {
          id: "4",
          name: "Penne al salmone",
          ingredients: "Pasta con salmone affumicato, panna e erbe aromatiche.",
          description: "Pasta con salmone affumicato, panna e erbe aromatiche.",
          prices: [{ name: PriceNameType.STANDARD, price: 15 }],
          imageUrl: "/api/serve-image?filename=1787049384593-941122783.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Pesce e derivati", "Latte e lattosio"],
        }
      ],
    },
    {
      name: "Secondi Piatti",
      description: "I nostri secondi fatti in casa",
      order: 2,
      items: [
        {
          id: "5",
          name: "Cotoletta alla milanese",
          ingredients: "Vitello impanato e fritto nel burro con limone.",
          description: "Vitello impanato e fritto nel burro con limone.",
          prices: [{ name: PriceNameType.STANDARD, price: 16 }],
          imageUrl: "/api/serve-image?filename=1787049384730-645220752.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Uova e prodotti a base di uova", "Latte e lattosio"],
        },
        {
          id: "6",
          name: "Pollo alla cacciatora",
          ingredients: "Pollo stufato con pomodoro, olive, capperi e rosmarino.",
          description: "Pollo stufato con pomodoro, olive, capperi e rosmarino.",
          prices: [{ name: PriceNameType.STANDARD, price: 14 }],
          imageUrl: "/api/serve-image?filename=1787049384867-697376836.webp",
          bestSeller: false,
          allergens: ["Sedano", "Solfiti (sopra 10 mg/l)"],
        },
        {
          id: "7",
          name: "Baccalà mantecato",
          ingredients: "Baccalà cremoso con olio e polenta morbida.",
          description: "Baccalà cremoso con olio e polenta morbida.",
          prices: [{ name: PriceNameType.STANDARD, price: 15 }],
          imageUrl: "/api/serve-image?filename=1787049385004-641085232.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Pesce e derivati"],
        },
        {
          id: "8",
          name: "Arrosto di maiale",
          ingredients: "Lombata di maiale al forno con latte e aromi.",
          description: "Lombata di maiale al forno con latte e aromi.",
          prices: [{ name: PriceNameType.STANDARD, price: 17 }],
          imageUrl: "/api/serve-image?filename=1787049385093-861022567.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Latte e lattosio", "Sedano"],
        },
        {
          id: "9",
          name: "Filetto al pepe verde",
          ingredients: "Manzo grigliato con salsa al brandy e pepe verde.",
          description: "Manzo grigliato con salsa al brandy e pepe verde.",
          prices: [{ name: PriceNameType.STANDARD, price: 20 }],
          imageUrl: "/api/serve-image?filename=1787049385229-13820348.webp",
          bestSeller: false,
          allergens: ["Senape", "Solfiti (sopra 10 mg/l)"],
        }
      ],
    },
    {
      name: "Contorni",
      description: "Contorni",
      order: 3,
      items: [
        {
          id: "10",
          name: "Patate arrosto",
          ingredients: "Patate novelle al forno con rosmarino e olio extravergine.",
          description: "Patate novelle al forno con rosmarino e olio extravergine.",
          prices: [{ name: PriceNameType.STANDARD, price: 5 }],
          imageUrl: "/api/serve-image?filename=1787049385366-424937928.webp",
          bestSeller: false
        },
        {
          id: "11",
          name: "Spinaci saltati",
          ingredients: "Spinaci freschi trifolati con aglio e limone.",
          description: "Spinaci freschi trifolati con aglio e limone.",
          prices: [{ name: PriceNameType.STANDARD, price: 5 }],
          imageUrl: "/api/serve-image?filename=1787049385505-445856704.webp",
          bestSeller: false
        },
        {
          id: "12",
          name: "Carote al vapore",
          ingredients: "Carote baby cotte al vapore con prezzemolo.",
          description: "Carote baby cotte al vapore con prezzemolo.",
          prices: [{ name: PriceNameType.STANDARD, price: 4 }],
          imageUrl: "/api/serve-image?filename=1787049385651-905501243.webp",
          bestSeller: false
        },
        {
          id: "13",
          name: "Broccoli al curry",
          ingredients: "Broccoli lessati con spezie leggere e olio.",
          description: "Broccoli lessati con spezie leggere e olio.",
          prices: [{ name: PriceNameType.STANDARD, price: 5 }],
          imageUrl: "/api/serve-image?filename=1787049385840-866310034.webp",
          bestSeller: false
        },
        {
          id: "14",
          name: "Insalata mista",
          ingredients: "Misticanza fresca con olio e aceto balsamico.",
          description: "Misticanza fresca con olio e aceto balsamico.",
          prices: [{ name: PriceNameType.STANDARD, price: 4 }],
          imageUrl: "/api/serve-image?filename=1787049385968-964207983.webp",
          bestSeller: false
        }
      ],
    },
    {
      name: "Dolci",
      description: "I nostri dolci fatti in casa",
      order: 4,
      items: [
        {
          id: "15",
          name: "Tiramisù",
          ingredients: "Mascarpone, caffè, savoiardi e cacao amaro.",
          description: "Mascarpone, caffè, savoiardi e cacao amaro.",
          prices: [{ name: PriceNameType.STANDARD, price: 7 }],
          imageUrl: "/api/serve-image?filename=1787049386073-543059543.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Uova e prodotti a base di uova", "Latte e lattosio"],
        },
        {
          id: "16",
          name: "Panna cotta",
          ingredients: "Crema di panna cotta con coulis di frutti di bosco.",
          description: "Crema di panna cotta con coulis di frutti di bosco.",
          prices: [{ name: PriceNameType.STANDARD, price: 6 }],
          imageUrl: "/api/serve-image?filename=1787049386144-37257487.webp",
          bestSeller: false,
          allergens: ["Latte e lattosio"],
        },
        {
          id: "17",
          name: "Crostata di frutta",
          ingredients: "Pasta frolla con crema pasticcera e frutta fresca.",
          description: "Pasta frolla con crema pasticcera e frutta fresca.",
          prices: [{ name: PriceNameType.STANDARD, price: 7 }],
          imageUrl: "/api/serve-image?filename=1787049386271-650416033.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Uova e prodotti a base di uova", "Latte e lattosio"],
        },
        {
          id: "18",
          name: "Zabaione",
          ingredients: "Crema con tuorli, zucchero e marsala caldo.",
          description: "Crema con tuorli, zucchero e marsala caldo.",
          prices: [{ name: PriceNameType.STANDARD, price: 6 }],
          imageUrl: "/api/serve-image?filename=1787049386383-27420003.webp",
          bestSeller: false,
          allergens: ["Uova e prodotti a base di uova", "Solfiti (sopra 10 mg/l)"],
        },
        {
          id: "19",
          name: "Cheesecake al limone",
          ingredients: "Base di biscotti con crema al formaggio e limone.",
          description: "Base di biscotti con crema al formaggio e limone.",
          prices: [{ name: PriceNameType.STANDARD, price: 7 }],
          imageUrl: "/api/serve-image?filename=1787049386480-679492360.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)", "Latte e lattosio"],
        }
      ],
    },
    {
      name: "Bevande",
      description: "Le nostre bevande sempre fresche e sempre a portata di mano",
      order: 5,
      items: [
        {
          id: "20",
          name: "Spritz",
          ingredients: "Aperol, prosecco, soda e arancia.",
          description: "Aperol, prosecco, soda e arancia.",
          prices: [{ name: PriceNameType.STANDARD, price: 6 }],
          imageUrl: "/api/serve-image?filename=1787049386588-3608306.webp",
          bestSeller: false,
          allergens: ["Solfiti (sopra 10 mg/l)"],
        },
        {
          id: "21",
          name: "Vino rosso Chianti",
          ingredients: "Vino toscano strutturato da sangiovese.",
          description: "Vino toscano strutturato da sangiovese.",
          prices: [{ name: PriceNameType.STANDARD, price: 8 }],
          imageUrl: "/api/serve-image?filename=1787049386755-951399847.webp",
          bestSeller: false,
          allergens: ["Solfiti (sopra 10 mg/l)"],
        },
        {
          id: "22",
          name: "Birra artigianale",
          ingredients: "Lager italiana non filtrata.",
          description: "Lager italiana non filtrata.",
          prices: [{ name: PriceNameType.STANDARD, price: 5 }],
          imageUrl: "/api/serve-image?filename=1787049386867-258212768.webp",
          bestSeller: false,
          allergens: ["Cereali contenenti glutine (grano, orzo, avena, ecc.)"],
        },
        {
          id: "23",
          name: "Caffè espresso",
          ingredients: "Espresso napoletano puro.",
          description: "Espresso napoletano puro.",
          prices: [{ name: PriceNameType.STANDARD, price: 1.5 }],
          imageUrl: "/api/serve-image?filename=1787049386987-103591403.webp",
          bestSeller: false
        },
        {
          id: "24",
          name: "Acqua naturale",
          ingredients: "Acqua frizzante o naturale da fonte italiana.",
          description: "Acqua frizzante o naturale da fonte italiana.",
          prices: [{ name: PriceNameType.STANDARD, price: 2 }],
          imageUrl: "/api/serve-image?filename=1787049387015-100930125.webp",
          bestSeller: false
        }
      ],
    }
  ],
};
