export const themeColors = {
  layout: {
    background: "#e5dae9",
    homeButtonColor: "#6c3483",
    homeButtonTextColor: "#f7f3ec",
  },
  navbar: {
    background: "#3f1e4c",
    logoColor: "#f7f3ec",
    textColor: "#f7f3ec",
    buttonBackground: "#4e255e",
    buttonText: "#f7f3ec",
    buttonHover: "#af8fbb",
    iconColor: "#f7f3ec",
  },
  sidebar: {
    background: "#3f1e4c",
    titleColor: "#f7f3ec",
    menuItemBackground: "#52355e",
    menuItemColor: "#f7f3ec",
    menuItemActive: "#4e255e",
    menuItemHover: "#4c245b",
    iconColor: "#f7f3ec",
  },
  drawer: {
    background: "#af8fbb",
    titleColor: "#16120e",
    menuItemColor: "#16120e",
    footerTextColor: "#6d666a",
  },
  card: {
    backgroundImage: "",
    backgroundOpacity: 1,
    backgroundColor: "#efe9f2",
    bestSellerTagColor: "#6c3483",
    productNameColor: "#16120e",
    priceColor: "#4e255e",
    ingredientsColor: "#6d666a",
    detailsButtonBackground: "#6c3483",
    detailsButtonIcon: "#f7f3ec",
    subtitleColor: "#16120e",
    detailsIngredientsColor: "#6d666a",
    descriptionTextColor: "#6d666a",
    shadowColor: "#1A1A17",
    shadowOpacity: 0.08,
    hoverShadowOpacity: 0.14,
    borderRadius: 18,
    borderColor: "#af8fbb",
    borderWidth: 1,
    detailsBorderColor: "#6c3483",
    detailsBorderWidth: 1,
    allergenTagColor: "#4e255e",
    allergenTextColor: "#f7f3ec",
    viewMode: "list",
    bestSellerTextColor: "#f7f3ec",
  },
  sections: {
    titleColor: "#16120e",
    descriptionColor: "#6d666a",
  },
  footer: {
    background: "#3f1e4c",
    textColor: "#f7f3ec",
    linkHoverOpacity: 0.8,
  },
  modelViewer: {
    ambientIntensity: 2,
  },
};
