export const themeColors = {
  layout: {
    background: "#FAF7F0",
    homeButtonColor: "#E0A32E",
    homeButtonTextColor: "#1A1A17",
  },
  navbar: {
    background: "#1A1A17",
    logoColor: "#E0A32E",
    textColor: "#FAF7F0",
    buttonBackground: "#E0A32E",
    buttonText: "#1A1A17",
    buttonHover: "#F2D08A",
    iconColor: "#FAF7F0",
  },
  sidebar: {
    background: "#1A1A17",
    titleColor: "#FAF7F0",
    menuItemBackground: "#1A1A17",
    menuItemColor: "#FAF7F0",
    menuItemActive: "#E0A32E",
    menuItemHover: "#F2D08A",
    iconColor: "#E0A32E",
  },
  drawer: {
    background: "#1A1A17",
    titleColor: "#FAF7F0",
    menuItemColor: "#FAF7F0",
    footerTextColor: "#EFE9DC",
  },
  card: {
    backgroundImage: "",
    backgroundOpacity: 1,
    backgroundColor: "#FFFFFF",
    bestSellerTagColor: "#E0A32E",
    productNameColor: "#1A1A17",
    priceColor: "#96640B",
    ingredientsColor: "#5C5A52",
    detailsButtonBackground: "#1A1A17",
    detailsButtonIcon: "#FAF7F0",
    subtitleColor: "#1A1A17",
    detailsIngredientsColor: "#5C5A52",
    descriptionTextColor: "#5C5A52",
    shadowColor: "#1A1A17",
    shadowOpacity: 0.08,
    hoverShadowOpacity: 0.14,
    borderRadius: 18,
    borderColor: "#EFE9DC",
    borderWidth: 1,
    detailsBorderColor: "#EFE9DC",
    detailsBorderWidth: 1,
    allergenTagColor: "#E0A32E",
    allergenTextColor: "#1A1A17",
    viewMode: "list",
  },
  sections: {
    titleColor: "#1A1A17",
    descriptionColor: "#5C5A52",
  },
  footer: {
    background: "#1A1A17",
    textColor: "#EFE9DC",
    linkHoverOpacity: 0.8,
  },
  modelViewer: {
    ambientIntensity: 2,
  },
};
